### PR TITLE
pass on maxDataPoints value to metric-tank

### PR DESCRIPTION
**Pull request by Dieterbe**
uses https://github.com/raintank/graphite-api/pull/5/files

### CODE REVIEW

**Comment by Dieterbe** [comment]
i also committed the handler for this in raintank-metric:
https://github.com/raintank/raintank-metric/commit/777dbbd3d829c1e3efc1eecd8953309766a1e064

**Comment by Dieterbe** [comment]
hmm weird.
i've been loading data in endpoint dashboards just fine, all dashboards seem to work. summary + individual ones. but now i enabled grafana alerting, and all the alerting queries seem to fail.
grafana:

```
2015/12/07 23:06:01 [D] job results - job:<Job> monitorId=3 generatedAt=2015-12-07 23:06:01.001202765 +0000 UTC lastPointTs=2015-12-07 23:05:31 +0000 UTC definition: <CheckDef> Crit: ''sum(t(streak(graphite("litmus.grafana.*.ping.error_state", "30s", "", "")) == 3 , "")) >= 3' -- Warn: '0' err:non-fatal: "graphite RequestError (http://graphite-api:8888/render?format=json&from=1449529501&target=litmus.grafana.%2A.ping.error_state&until=1449529531): Get failed: 500 INTERNAL SERVER ERROR\n<no traceback found in response>" res:Unknown
```

graphite:

```
==> /var/log/raintank/graphite-flask.log <==
2015-12-07 23:01:01 ERROR    flask.app       {"event": "Exception on /render [GET]", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/app.py\", line 409, in render\n    series_list = evaluateTarget(context, target)\n  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/app.py\", line 493, in evaluateTarget\n    result = evaluateTokens(requestContext, tokens)\n  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/app.py\", line 503, in evaluateTokens\n    return evaluateTokens(requestContext, tokens.expression)\n  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/app.py\", line 508, in evaluateTokens\n    return fetchData(requestContext, tokens.pathExpression)\n  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/render/datalib.py\", line 158, in fetchData\n    return _fetchData(pathExpr, startTime, endTime, requestContext, seriesList)\n  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/render/datalib.py\", line 112, in _fetchData\n    time_info, series = finder.fetch_multi(nodes, startTime, endTime)\n  File \"/usr/local/lib/python2.7/dist-packages/graphite_raintank.py\", line 191, in fetch_multi\n    data = self.fetch_from_tank(nodes, start_time, end_time)\n  File \"/usr/local/lib/python2.7/dist-packages/graphite_raintank.py\", line 247, in fetch_from_tank\n    if g.maxDataPoints:\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/local.py\", line 342, in __getattr__\n    return getattr(self._get_current_object(), name)\nAttributeError: '_AppCtxGlobals' object has no attribute 'maxDataPoints'"}
^C
root@graphite:/# grep -R maxDataPoints /usr/local/lib/python2.7/dist-packages/
Binary file /usr/local/lib/python2.7/dist-packages/graphite_raintank.pyc matches
/usr/local/lib/python2.7/dist-packages/graphite_raintank.py:        if g.maxDataPoints:
/usr/local/lib/python2.7/dist-packages/graphite_raintank.py:            params['maxDataPoints'] = g.maxDataPoints
Binary file /usr/local/lib/python2.7/dist-packages/graphite_api/app.pyc matches
/usr/local/lib/python2.7/dist-packages/graphite_api/app.py:    if 'maxDataPoints' in RequestParams:
/usr/local/lib/python2.7/dist-packages/graphite_api/app.py:                float(RequestParams['maxDataPoints']))
/usr/local/lib/python2.7/dist-packages/graphite_api/app.py:            request_options['maxDataPoints'] = mdp
/usr/local/lib/python2.7/dist-packages/graphite_api/app.py:            g.maxDataPoints = mdp
/usr/local/lib/python2.7/dist-packages/graphite_api/app.py:            errors['maxDataPoints'] = 'Must be an integer.'
/usr/local/lib/python2.7/dist-packages/graphite_api/app.py:            if 'maxDataPoints' in request_options and any(context['data']):
/usr/local/lib/python2.7/dist-packages/graphite_api/app.py:                        series, request_options['maxDataPoints'],
```

**Comment by woodsaj** [comment]
@Dieterbe it is expected that g.MaxDataPoints is not set, as no maxDataPoints variable is sent with the request.

in graphite_raintank.py  either catch the exception or use  `g.get('maxDataPoints', none)` instead.

http://flask.pocoo.org/docs/0.10/api/#flask.g

**Comment by Dieterbe** [comment]
cool thanks that was it. @woodsaj i'll leave you the honor of merging the PR's for graphite-api and graphite-raintank :) seems to work fine now.

**Pull request merged**
